line-length = 88
indent-width = 4
target-version = "py313"

[lint]
select = ["E", "F", "I", "W"]  # Errores, warnings, imports, etc.
ignore = ["E501"]              # Ejemplo: ignora líneas largas

[format]
quote-style = "double"
indent-style = "space"
